
kind: pipeline
name: Spring_Vue_Template
# 通过.Dockerfile来构建镜像
steps:
- name: Docker build 
  image: plugins/docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    username: ${username}
    password: ${password}
    tags:
    - latest
    repo: ${repository_url}
    registry: ***
    dockerfile: Dockerfile

- name: Ssh commands
  image: appleboy/drone-ssh
  settings:
    host: ****
    username: ****
    repo: ${org_secret}
    password:
      from_secret: ${secret_name}
    port: 22
    script:
      - echo ====暂停容器开始=======
      - docker stop `docker ps -a| grep ${镜像名} | awk '{print $1}' `
      - docker rm -f `docker ps -a| grep ${镜像名} | awk '{print $1}' `
      - echo ====开始部署=======
      - docker run -detach --publish ****:80 --name=${镜像名}  --restart=always ${repository_url}:latest
      - echo ====部署成功======

- name: DingTalk notification
  image: guoxudongdocker/drone-dingtalk 
  settings:
    repo: ${org_secret}
    token:
      from_secret: ${secret_name}
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
  when:
    status: [failure, success]

volumes:
- name: cache
  host:
    path: /var/lib/cache 
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - master
